version: "3"
services:
  postgres:
    container_name: quizhub-postgres
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: quizhub-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "172.17.0.1:5432:5432"

  pgadmin4:
    container_name: quizhub-pgadmin4
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_USERNAME: wassim
      PGADMIN_DEFAULT_EMAIL: wassimrached@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 7777
    ports:
      - "172.17.0.1:7777:7777"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
