spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/quizhub-test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect