app:
  APP_VERSION: ${APP_VERSION:0.0.0}
  CORS:
    ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    ALLOWED-METHODS: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    ALLOWED-HEADERS: ${CORS_ALLOWED_HEADERS:*}
    EXPOSED-HEADERS: ${CORS_EXPOSED_HEADERS:*}
    ALLOW-CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:true}
    MAX-AGE: ${CORS_MAX_AGE:3600}

spring:
  application:
    name: quiz-hub
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}