spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/quizhub-exp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
rate:
  limit: 3
time:
  duration:
    in:
      minutes: 1