rate:
  limit: ${RATE_LIMIT_REQUESTS:10}
time:
  duration:
    in:
      minutes: ${RATE_LIMIT_TIME_DURATION_IN_MINUTES:5}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:172.17.0.1}:${DB_PORT:5432}/${DB_NAME:quizhub-dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}