name: Push Release to Image Registry
run-name: Pushing @${{ github.event.release.tag_name || github.event.inputs.releaseTag }} to Image Registry

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release Tag to Deploy'
        required: false

jobs:
  deploy:
    name: Deploy Release - @${{ github.event.release.tag_name || github.event.inputs.releaseTag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Clean the application
        run: mvn clean

      - name: Test the application
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/quizhub:${{ github.event.release.tag_name || github.event.inputs.releaseTag }}