name: Continuous Integration
run-name: CI Pipeline
concurrency: CI-${{ github.repository }}-${{ github.ref }}

on:
    pull_request:
        branches:
          - dev

jobs:
    build-test:
      name: Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: 21

        - name: Unit Tests
          run: mvn -B test --file pom.xml

        - name: Build the application
          run: |
            mvn clean
            mvn -B package --file pom.xml

        - name: Upload test results
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: target/